#!/bin/bash

# Kubectl Module - Installation and management for kubectl
# Generated by DevMachine AI system

readonly MODULE_NAME="kubectl"
readonly DOWNLOAD_DIR="${HOME}/Downloads"
readonly INSTALL_DIR="${HOME}/.devmachine/tools/${MODULE_NAME}"

# Utility functions
log_info() { echo "[INFO] $*"; }
log_warn() { echo "[WARN] $*"; }
log_error() { echo "[ERROR] $*"; }
log_success() { echo "[SUCCESS] $*"; }

# Get latest stable version
get_latest_version() {
    curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
}

# Check if kubectl is installed
check_installed() {
    local version="$1"
    local kubectl_path="${INSTALL_DIR}/kubectl"

    if [[ -x "${kubectl_path}" ]] && [[ "$(${kubectl_path} version --client --short)" == *"v${version}"* ]]; then
        return 0
    fi
    return 1
}

# Install kubectl
install_kubectl() {
    local version="${1:-$(get_latest_version)}"

    if check_installed "${version}"; then
        log_success "kubectl v${version} is already installed"
        return 0
    fi

    log_info "Installing kubectl v${version}..."

    # Create installation directory
    mkdir -p "${INSTALL_DIR}"

    # Download kubectl
    local download_url="https://storage.googleapis.com/kubernetes-release/release/${version}/bin/linux/amd64/kubectl"
    log_info "Downloading from: ${download_url}"

    if ! curl -L -o "${INSTALL_DIR}/kubectl" "${download_url}"; then
        log_error "Failed to download kubectl"
        return 1
    fi

    # Make executable
    chmod +x "${INSTALL_DIR}/kubectl"

    # Add to PATH if not already there
    if ! grep -q "${INSTALL_DIR}" ~/.bashrc 2>/dev/null; then
        echo "export PATH=\"${INSTALL_DIR}:\${PATH}\"" >> ~/.bashrc
        log_info "Added to PATH in ~/.bashrc"
    fi

    log_success "kubectl v${version} installed successfully"
    log_info "Please run: source ~/.bashrc"
}

# Remove kubectl
remove_kubectl() {
    if [[ ! -d "${INSTALL_DIR}" ]]; then
        log_warn "kubectl is not installed"
        return 0
    fi

    read -p "Remove kubectl from ${INSTALL_DIR}? (y/N): " confirm
    [[ "${confirm}" =~ ^[Yy]$ ]] || return 0

    log_info "Removing kubectl..."

    # Remove installation
    rm -rf "${INSTALL_DIR}"

    # Remove from PATH
    if [[ -f ~/.bashrc ]]; then
        sed -i.bak "/export PATH=\"${INSTALL_DIR}:/d" ~/.bashrc
        sed -i.bak "/export PATH=\".*${INSTALL_DIR}:/d" ~/.bashrc
    fi

    log_success "kubectl removed successfully"
}

# Check kubectl status
check_kubectl_status() {
    if [[ ! -x "${INSTALL_DIR}/kubectl" ]]; then
        echo "Status: Not installed"
        return 1
    fi

    local version
    version=$("${INSTALL_DIR}/kubectl" version --client --short 2>&1)
    echo "Status: Installed"
    echo "Version: ${version}"
    echo "Path: ${INSTALL_DIR}/kubectl"
    echo "Config: ${HOME}/.kube/config"
}

# Main module interface
install() {
    local version="${1:-}"
    install_kubectl "${version}"
}

remove() {
    remove_kubectl
}

status() {
    check_kubectl_status
}

# Entry point for direct execution
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        install|remove|status)
            "$@"
            ;;
        *)
            echo "Kubectl Module for DevMachine"
            echo "Usage: ${0} {install|remove|status} [version]"
            exit 1
            ;;
    esac
fi