name: Bug Report
description: Report a bug to help us improve DevMachine
title: "[Bug]: "
labels: ["bug"]
assignees: ["saurabhkrtiwari"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'devmachine ...'
        2. See error...
        3. Expected behavior...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DevMachine Version
      description: Version of DevMachine (run `devmachine --version`)
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Ubuntu version, kernel, etc.
      placeholder: |
        Ubuntu: 20.04
        Kernel: 5.4.0-65-generic
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, logs, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues
          required: true
        - label: I have read the documentation
          required: true
        - label: I have provided all requested information
          required: true